function  deployFolder = getDeployFolder()
root = getenv('HALCONROOT');
halconVersion = regexp(root, '(?<=HALCON-)(\d|\.)*', 'match', 'once');
thisFolder = fileparts(mfilename('fullpath'));
deployFolder = fullfile(fileparts(thisFolder), ...
    sprintf('halcon-%s-%s-%s', ...
    halconVersion, ...
    computer('arch'), ...
    lower(mex.getCompilerConfigurations('C++').ShortName)));
end

